// Ejercicio 2: Multiplicación y División
let numero3 = 8;
let numero4 = 4;

// Realiza la multiplicación de numero3 y numero4
let resultadoMultiplicacion = numero3 * numero4;
console.log(`El resultado de ${numero3} multiplicado por ${numero4} es: ${resultadoMultiplicacion}`);

// Realiza la división de numero3 entre numero4
let resultadoDivision = numero3 / numero4;
console.log(`El resultado de ${numero3} dividido por ${numero4} es: ${resultadoDivision}`);
